### ISSUE TITLE
Error in lab in explanation

### ISSUE THREAD

**Issue by ritterob** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#1]
# Module: 01
#### Step: 16

Your description on the network bindings and what they do is completely wrong. Y'all obviously don't know what network bindings are. This does *not* mean that “all email sent from the Internet and from IP address 172.16.0.11 through port 25 will be received by this new connector”, but rather that the locally attached NIC with IP 172.16.0.11 will be the *only* NIC that uses this connector.

Repro steps:

1.
1.
1.

**Comment by tfrink** [comment]
Thanks Ritterob for the feedback. We'll include this in our updates for the next release of the course.
