### ISSUE TITLE
Module 3 – Lab 3 - Exercise 1 - Create Hygiene Filters -- Microsoft 365 Admin Center/Admin Centers/Security no longer brings user directly to Office 365 Security & Compliance center

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#10]
# Module: 03
#### Step: 03

**Description of issue**

Task 1/Step 3 (and subsequent steps) no longer work as-written as it seems the default links no longer direct to the Office 365 Security & Compliance center 

**Repro steps:**
Task 1/Step 3:

- If one follows this verbatim, opening the 'Security' entry brings us to the 'Microsoft 365 Defender' site ( https://security.microsoft.com/homepage ) where the subsequent instructions in this Task, and through to the end of the lab will not work as-written.

- This is likely due to changes and updates since the course was originally written, and it is perhaps recommended to include a 'Note' in addition to (or in place of Step 3) which will step the users through an alternate method to arrive at the Office 365 Security & Compliance center.

- At least as-of this post, one could access this site by (from the MSFT 365 Admin Center) accessing the 'Security' entry, going to the 'Microsoft 365 Defender' site, scrolling to the bottom on the left and selecting the 'More resources' entry, and then scrolling through the various addt'l resources to select 'open' on the 'Office 365 Security & Compliance center' entry:

![image](https://user-images.githubusercontent.com/49700217/131746553-15305878-e98e-4554-9fc8-1e8d82e28580.png)

- One can also simply browse directly there by going to https://protection.office.com/homepage

**Comment by tfrink** [comment]
Thanks Tester. I have updated all the lab instructions in this exercise to use the new Microsoft 365 Defender portal. Unfortunately, for some reason I have lost write access to MS-203, so I can't merge my changes into the master branch. I'll have to wait until George S. gets back in the office next week to commit my changes.
