### ISSUE TITLE
Module 8 - Lab 7 - Exercise 3 - Test your Hybrid Deployment -- Typo in account name

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#102]
# Module 8
##### Step 12

Replace:

Under Account with privileges field enter **Adatum/Admim**.

With

Under Account with privileges field enter **Adatum\Administrator**.

**Comment by maquinl** [comment]
Thanks for bringing this to our attention, i have fixed the type and the update is live.
