### ISSUE TITLE
Missing instructions to create on-prem mailboxes.

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#105]
# Module: 07
## Lab/Demo: 6

Exercise: 3

Introduction

Description of issue

The introduction says, "In the earlier lab on Implementing ActiveSync, you created on-premises user mailboxes for Holly [Dickson], Paul Wimmer, and Jessica Hofer. Each mailbox was created in the on-premises adatum.com domain on LON-EX1."

However, that Active Sync lab has been removed from the course, so the instructions to create these three mailboxes have disappeared.  Please could they be added back in to the lab instructions?  Maybe as part of Lab 1, because that's where you're first using the Exchange Server Admin Center?

**Comment by maquinl** [comment]
Hi @AnnetteGill - these issues have been addressed and will be published in an upcoming lab refresh (scheduled for 10/21)

Thanks!

**Comment by AnnetteGill** [comment]
Thank you!
