### ISSUE TITLE
Dns decondary zone

### ISSUE THREAD

**Issue by Mr-Robi** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#12]
# Module: 10
#### Step: 00

Description of issue
In the course there is a dns secondary zone creation on ex1 that here is not present.
Exchange server has 2 network cards and 3 ip address, two private (one used for dns zone tranfer from domain controller) fixed on first network card and one pubblic on the second card. The pubblic ip address is exposed on Internet and  exchenge answers to external dns requests from there.
Domain controller in fact has only a private ip and use another gateway with Nat. It is not reachable from Internet. 
During hybrid configuration steps it is necessary to add a domain and validate it adding dns records. 
Exchange is the only server exposed with a pubblic ip address. The secondary zone is necessary  on that server to permit domain validation. (If I understand how it works ofcourse)

Bests, Rob

**Comment by maquinl** [comment]
Thank you for your feedback, we will take this into consideration during our next review. With the current lab steps, if this is causing any issues, please be sure to reopen this and leave further feedback.
