### ISSUE TITLE
Exchange Admin Center Failed to update the accepted domain.

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#121]
# Module 12 - Lab 10 - Exercise 1 - Configure Your Hybrid Deployment
#### Step: 18

We are unable to update the accepted domain. It is not just the case with one custom domain, the issue is occurring with all the accepted domains. We cannot update them. 
This is a blocking issue and the lab is not usable after this. There are several different users who are facing this error. Please help fix this. 
 
![image](https://user-images.githubusercontent.com/52242119/206793373-5cdac4ca-5da1-4c6e-bddc-0373ad39988b.png)
![image](https://user-images.githubusercontent.com/52242119/206793727-6463ba5a-8700-411e-b45f-5eccabd8850e.png)

**Comment by maquinl** [comment]
Hi @sehrish777 - It looks like you are referring to lab steps that are out of date (by over a year). The current (updated) labs can be found in this repository here:
https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/tree/master/Instructions/Labs

Specifically, Lab 7 Excersise 2 task 2: 
https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/blob/master/Instructions/Labs/LAB_07_Ex2_Configure_Hybrid_Deployment.md 

after testing lab 7, i am not experiencing the same behavior. I would recommend reaching out to your lab hosting provider to ensure they updates their labs with the correct steps - and for the time being reference the steps from within github linked above.  

Please let me know if you reproduce the issue after using the updated lab and i will re-open this issue. Thanks!
