### ISSUE TITLE
Lab 7, Ex 2 - the configure button doesn't download the wizard

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#123]
#### Step 8

Clicking the configure button does not launch the ClickOnce installation of the Hybrid Configuration Wizard. Instead, it opens a Bing search page. It looks like Microsoft have a typo in the link. I've tried this in Edge on various machines, including my desktop machine.

The workaround is to open a new browser tab and navigate to the following.

https://aka.ms/hybridwizard

**Comment by maquinl** [comment]
Hi @craigbeeremct - thanks for the feedback. I have reproduced the same behavior and will be reaching out internally to see if we can get this resolved. In the interim, i have added a note in step 8 with a workaround of navigating to https://aka.ms/hybridwizard.

Thanks again!
