### ISSUE TITLE
Lab 7, Ex 1 - Downloading AD Connect (UI drift issue perhaps?)

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#124]
#### Steps: 3-7

Description of issue
The AD Connect isn't available from the Microsoft 365 Admin Center.

Replace steps 3 through 7 with the following.

In the **Microsoft 365 Admin Center**, select **Azure Active Directory** in the **Admin centers** section.

In the **Azure Active Directory admin center**, select **Azure Active Directory** in the shortcut menu. Select **Azure AD Connect** in the **Manage** section of the blade menu. Select **Download Azure AD Connect** in the details pane.

**Comment by maquinl** [comment]
Hi Craig, work is being done to incorporate the new "Add or sync users to ‎Microsoft 365‎" wizard into the instructions in the next update (this is now the default experience when clicking "Directory Synchronization"). For the time being, we have a note in step 4 with a direct link to download the AD Connect tool.

Thanks for the feedback!
