### ISSUE TITLE
Lab 7, Ex 2 - Accepted domains, error in portal

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#125]
#### Step: 18

Description of issue
All of us this week received an error from the Exchange Online EAC when trying to set the domain to Internal Relay.
Failed to update the accepted domain, 
Error: Error executing cmdlet

Workaround
Use the ExchangeOnlineManagement PowerShell module.

Get-AcceptedDomain -Identity "xxxUPNxxx.xxxCustomDomainxxx.xxx" | Set-AcceptedDomain -DomainType InternalRelay

**Comment by craigbeeremct** [comment]
Screenshot of issue
![Exchange Online EAC accepted domain error](https://user-images.githubusercontent.com/71042835/207950685-c0e854bd-0f5f-490b-80ea-cc9ef9e68286.png)

**Comment by maquinl** [comment]
Hi Craig, i have added this PowerShell workaround to the lab instructions under step 18 while we investigate this issue further.
