### ISSUE TITLE
Error running HCW in lab 7

### ISSUE THREAD

**Issue by hbud** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#133]
# Module: 07
#### Step: 17

Description of issue
Connecting to Exchange Online PowerShell in the HCW uses Remote PowerShell, this is now deprecated and for tenants created after April 1 it is automatically disabled. Running the HCW generates an error.
Until late September we can re-enable RPS in the tenant.
See the following post:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-remote-powershell-in-exchange-online-re-enabling/ba-p/3779692
This contains the temporary fix until the HCW is updated.

**Comment by maquinl** [comment]
Thank you for the feedback, i will be testing the issues you pointed out and will reply once the instructions have been updated.

**Comment by maquinl** [comment]
[A PR](https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/pull/139) has been submitted including a temporary workaround to this issue and will be merged into Master by 8pm EST tonight. Thanks!
