### ISSUE TITLE
Lab 7, ex 2, downloading Azure AD Connect has changed

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#137]
# Learning Path: 07
# Lab/Demo: 07
#### Step: 05

Description of issue

The process for obtaining Azure AD Connect has changed.  You have to go through a wizard before you can download the tool, so the instructions need to be updated.

**Comment by maquinl** [comment]
[A PR](https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/pull/139) has been submitted including updated lab steps and will be merged into Master by 8pm EST tonight. Thanks!
