### ISSUE TITLE
Lab 7, Ex 1, Hybrid Configuration Wiazard must be run from the new EAC

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#138]
# Learning Path: 07
#### Step: 7 to 10

Description of issue

The Hybrid Configuration Wizard can't be run from the Classic Exchange Admin Center now - it must be run from the new one.  So the instructions need to be updated.

**Comment by maquinl** [comment]
Thank you for the feedback, i will be testing all issues pointed out and will reply once the instructions have been updated.

**Comment by maquinl** [comment]
[A PR](https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/pull/139) has been submitted including updated lab steps and will be merged into Master by 8pm EST tonight. Thanks!
