### ISSUE TITLE
Out of date steps in lab02

### ISSUE THREAD

**Issue by ntuohy** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#14]
# Module: 02
#### Step: 10

Description of issue
Step 10 states: On the left-hand navigation bar, in the Admin centers section, select Exchange. This opens the **classic** Exchange admin center for Exchange Online.

This is not the case and hasn't been for some months now. 
This should read: On the left-hand navigation bar, in the Admin centers section, select Exchange. This opens the **Modern** Exchange admin center for Exchange Online.

Then step 11 could read: In the Exchange Admin center, in the left-hand navigation expand **Mail flow**

Step 12 could then read: In the left-hand navigation pane, select **Rules**  
Everything else could then stay the same and we can now create the rules in the Modern interface not the old classic...

**Comment by maquinl** [comment]
Thanks for your feedback, we have included text to revert back to classic admin center for now, and the fix has been pushed.
