### ISSUE TITLE
Lab 5 - Exercise 1 - Manage Roles and Permission Policies - UI Change

### ISSUE THREAD

**Issue by HashirSajjad** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#140]
# Lab: 05
#### Step: 03

Description of issue
When the classic exchange admin center is clicked , the mailbox does not load for recipients and says that this feature has moved to the New Exchange admin center.

Relevant Screenshot:
![image](https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/assets/82022081/52ca1c14-d7c8-44d8-a3e6-3dc60ddf3104)

**Comment by maquinl** [comment]
@HashirSajjad thanks for the feedback. The instructions have been updated to reflect the new exchange admin center experience.
