### ISSUE TITLE
issue with public ip

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#143]
Your answer 👍 I would recommend that you bring this up with your lab hosting provider, GoDeploy. For the time being, the labs in GitHub are the most up to date.

But in the github m365 cannot connect to the onprem VM as no public ip !!!!
So how can you verify the dns record TXT

**Comment by maquinl** [comment]
@chrzanowskiItta Following the github instructions works as expected. the public IP and UPN are provided by your lab hosting provider

![image](https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/assets/37308730/e2e83d56-13eb-4254-b011-95ff9a413c29)
