### ISSUE TITLE
issue with ad connect set-msoldirsyncenabled !!!!

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#144]
Module prepare for hybrid sync
I have in the ad connect task step 26
this error message
HELP
![image](https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/assets/26869408/1fe70285-e447-4d95-b8eb-77de9d047b27)

thanks

**Comment by maquinl** [comment]
see https://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging/issues/145
