### ISSUE TITLE
Lab 1 – Lab Introduction 172.16.0.11 ?!

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#146]
Exercise 1 - Create Connectors
Task 2 - Create a Custom Receive Connector

I have a question about the receive connector
In step 15 we must put an ip 172.16.0.11
**This ip corresponds to what?**
and what is this address for ?

**Comment by maquinl** [comment]
the new receive connector that you are creating must have a unique combination of IP address and port number that is different from any existing receive connectors. We use "172.16.0.11" as a random private IP address (not a public range address) to demonstrate creating the custom receive connector for the lab. In theory, and random IP would work. We don't build on top of this receive connector in other labs -we only create it.

**Comment by chrzanowskiItta** [comment]
hello thanks but when I read this note
**Note**: By updating this network adapter binding, all email sent from the Internet and from IP address 172.16.0.11 through port 25 will be received by this new connector, which in turn will send it to Adatum's Exchange Server.
so in hybrid when exchange online will send email to my on premise it will by this ip ?
so it is important !!

**Comment by chrzanowskiItta** [comment]
and why do you create this connector as there is already one Default LON-ex1 who accept any domains (star *)
tks for the understating of the architecture
