### ISSUE TITLE
New page, Users and domains, creating Threat Management Policies

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#5]
# Module: 3
#### Step: Between 8 and 9

Description of issue

In the Task "Create a Malware Filter", between steps 8 and 9, there is now an additional page to fill out, "Users and Domains". It is not optional.

Repro steps:

1. Go to Office 365 Security & Compliance
1. Open Policy
1. Create a new Policy (e.g. Antimalware)
1. Name and describe the policy and hit next
1. New page, "Users and domains", not mentioned in the lab instructions. You must enter something to continue.

![users and domains on office security center](https://user-images.githubusercontent.com/47234227/118863228-a0682e80-b8ac-11eb-8dcc-53702b445630.JPG)

**Comment by FireyJoe** [comment]
In https://github.com/MicrosoftLearning/MS-500-Microsoft-365-Security/pull/80, it was pointed out that entering "All Users" under "Groups" should work here. We also had success entering the full domain of the tenant under "Domains", but I'm not sure if they are strictly equivalent. The instructions should be updated to accommodate the changes to the site.

**Comment by geschwei** [comment]
thank you for your insight I will be looking into this issue.

**Comment by LodsCory** [comment]
Just wanted to bump this as we are seeing more issues on our end regarding this.

**Comment by davemct** [comment]
This will not work AT ALL.  All Users does no longer shows up as a group.  Only two groups exist on the tenant, All Company and Contoso.

No matter which group I select, at the end the Submit button generates and error.

I'm teaching this tomorrow, so we'll sadly have to skip this lab.

![image](https://user-images.githubusercontent.com/19361686/122659203-1f19eb00-d13b-11eb-9417-b76575a76a3e.png)

**Comment by davemct** [comment]
Final thing...

I found this:
![image](https://user-images.githubusercontent.com/19361686/122659400-8fc20700-d13d-11eb-84bc-9acb5ce32eb2.png)

Which is the admin page the lab steps where written for.

If I click the + symbol, I'll get the following page, which aligns with the lab steps:

![image](https://user-images.githubusercontent.com/19361686/122659469-22fb3c80-d13e-11eb-8fa5-fb1161f93005.png)

**Comment by StevenLODS** [comment]
Bumping this.

**Comment by geschwei** [comment]
Hi Everyone, after several attempts to run the anti-malware policy from the new UI, I am seeing the same issue without any change in the last month. So I will re-write task 1 to use the Exchange admin center. I will have the steps available by the 25th.

**Comment by davemct** [comment]
Thanks!  If you need any help, testing or otherwise, just let me know.  

Dave Franklyn

**Comment by geschwei** [comment]
I have just resolved this issue. the problem was that the security&compliance role needed to be updated. For ease of use. I used the Organization management group stop any issues that might arise due to permissions.
