### ISSUE TITLE
Github access for students OK?

### ISSUE THREAD

**Issue by davemct** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#6]
# Module: 00 Skillpipe online book

Description of issue  The first page, Course Introduction, has a link to this Github page.  I thought the Microsoft Learning GitHub area was only for the MCTs?  I don't mind students going here at all, and used to invite them, but a training vendor I occasionally work for told me not to, citing that MSL said MCTs only.

Can Microsoft Learning comment on this, please?

Dave

**Comment by geschwei** [comment]
Hi Davemct,

I have not heard of any reason why a student wouldn't be able to visit the course sites. 

I am the course owner for MS-203.
