### ISSUE TITLE
AntiSpam Policy wizard completely different and instruction not compatible with new interface.

### ISSUE THREAD

**Issue by billwood44** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#7]
# Module: 03
#### Step: 00

Description of issue

The anti-spam policies creation is now completely different.
Repro steps:

There are now 2  default anti-spam policies, inbound and outbound.  
The instructions in the lab manual cannot be extrapolated to indicate what should be done.  This lab task needs to be rewritten to match the current wizard/portal configuration options.
![AntiSpamPolicyNewWizard](https://user-images.githubusercontent.com/16070952/121788136-d2fa0400-cb98-11eb-87db-cf477e57977f.PNG)

**Comment by geschwei** [comment]
thank you for your insight bill,

ill will look in to this issue.

**Comment by geschwei** [comment]
i have resolved the issue and updated the task.
