### ISSUE TITLE
Lab 9 receives 410 Error

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#88]
# Module: 09
#### Step: 06

When attempting to sign in and setup the Hybrid Exchange Server, a 410 error appears saying the page has been removed. 

![image](https://user-images.githubusercontent.com/48496971/173686099-f6618e2e-7170-478d-8472-fdb052fdb319.png)

**Comment by maquinl** [comment]
Hi AMorin8787, looks like we will have to modify these steps to reflect using office 365 to migrate the mailbox rather than on-prem EAC. I have tested the new steps and will update the lab accordingly. Thanks!
